### PR TITLE
add heatmap analysis

### PR DESCRIPTION
**Pull request by vpchung**

### CODE REVIEW

**Review by bswhite — COMMENTED** [review]
Nicely commented. The code looks good and readable. The logic also looks good, though the std dev cutoff is a bit too aggressive. Let's talk about this during our meeting.

Other minor points:
1. I've taken to using pacman to include libraries -- for many libraries, though not necessarily all, it will install the library if it isn't already. e.g., I did not have pheatmap installed, so this
library(pheatmap)
failed. Instead I would do:
suppressPackageStartupMessages(library(pacman))
suppressPackageStartupMessages(p_load(pheatmap))

Note "p_load" in the second line.

This isn't a big deal here, where you only have a few libraries. But, occasionally I have analysis code with many library imports. When I run it in a new environment, it will break on the first un-installed library. I will install that library. Re-run the code, which will break on the next un-installed library. etc. It is much more efficient for R to automatically install missing packages using p_load.

2. Can you save the heatmaps to pngs? I see the pngs in the repo, but not they are outputted in the code.

**Comment by vpchung** [comment]
Thanks, Brian!  I have modified the script to include your suggestions.

Additionally, the two matrices have been generated and exported as two RDS objects. I have configured the script so that these will be loaded for you upon running the code.

**Review by bswhite — APPROVED** [review]
Thanks, Verena.

**Review by bswhite — APPROVED** [review]

**Review by bswhite — APPROVED** [review]

**Review by bswhite — COMMENTED** [review]
@vpchung, I find this remapping hard to read. The idiom you used above seems a lot more straightforward:
`#   rownames_to_column("Gene") %>%                                                                                  
#   left_join(gene_symbols, by = "Gene") %>%                                                                        
#   select(-Gene) %>%                                                                                               
#   column_to_rownames("Symbol")           `

**Comment by vpchung** [comment]
Ah right, there might've been a less complex way to go about it, but what I had written was essentially to:

1. re-add the gene symbols to the `filtered.rnaseq` dataframe by joining it with the `gene_symbols` dataframe (by the column, "Gene")

```
left_join(gene_symbols, by = "Gene") %>%
```

2. remove the "Gene" column from the df since it is no longer needed (all the other columns will remain)

```
select(-Gene)
```

3. use the gene symbols as the rownames

```
column_to_rownames("Symbol") 
```

I hope that makes a little more sense?

**Comment by bswhite** [comment]
Sorry -- the context of my comment wasn't clearly. Thanks for your explanation -- but that code (i.e., starting with left_join) I understood and is clean and clear. This code:
`colnames(p.mat) <- gene_symbols$Symbol[which(gene_symbols$Gene %in% colnames(p.mat))]

 colnames(c.mat) <- gene_symbols$Symbol[which(gene_symbols$Gene %in% colnames(c.mat))]`

Seems fragile to me. Could you change to use the left_join-style code?

**Comment by bswhite** [comment]
Sorry -- the context of my comment wasn't clearly. Thanks for your explanation -- but that code (i.e., starting with left_join) I understood and is clean and clear. This code:
`colnames(p.mat) <- gene_symbols$Symbol[which(gene_symbols$Gene %in% colnames(p.mat))]

 colnames(c.mat) <- gene_symbols$Symbol[which(gene_symbols$Gene %in% colnames(c.mat))]`

Seems fragile to me. Could you change to use the left_join-style code?

**Comment by bswhite** [comment]
Sorry -- the context of my comment wasn't clearly. Thanks for your explanation -- but that code (i.e., starting with left_join) I understood and is clean and clear. This code:
`colnames(p.mat) <- gene_symbols$Symbol[which(gene_symbols$Gene %in% colnames(p.mat))]

 colnames(c.mat) <- gene_symbols$Symbol[which(gene_symbols$Gene %in% colnames(c.mat))]`

Seems fragile to me. Could you change to use the left_join-style code?

**Comment by vpchung** [comment]
Unfortunately, I get errors about non-unique values when I attempt to use the similar approach for the matrices.  What I attempted was:

```
p.mat %>% 
    t %>%
    as.data.frame() %>%
    rownames_to_column("Gene") %>%
    left_join(gene_symbols, by = "Gene") %>%
    select(-Gene) %>%
    column_to_rownames("Symbol")
```

where I traversed the matrix first, then converted it to a dataframe. 

I'm not sure if there is a tidyverse way of renaming column names (rather than row names), which was why I used the base-R approach noted above.

**Comment by vpchung** [comment]
I just tried something like this, but to no avail:

```
p_load(janitor)

p.mat %>%
    t %>%
    as.data.frame() %>%
    rownames_to_column("Gene") %>%
    left_join(gene_symbols, by = "Gene") %>% 
    select(-Gene) %>% 
    as.matrix %>% 
    t %>% 
    janitor::row_to_names(-1)
```

**Pull request merged**
